### ISSUE TITLE
Feature/enter records button

### ISSUE THREAD

**Issue by susanX** [yalla-coop/curenetics#106]
Remove the white background from the plus in circle button.
Make all dropdown menus 16px or near
Make mobile form one column.

**Comment by othman-shamla** [comment]
can you explain more please?
this is in (Enter patient data manually) page?

**Comment by susanX** [comment]
The button is on the enter-patients page.
The problem was the button had a white fill and it should have a clear background.
plus in circle, Click to add another patient's medical details.
I sent you the button with a clear fill to the circle on your personal Slack.
Thanks
