### ISSUE TITLE
Nav bar items - Home only

### ISSUE THREAD

**Issue by susanX** [yalla-coop/curenetics#107]
This is to encourage the app use to be in one direction.
Show Home top right in the nav bar. No other items will show.

**Comment by othman-shamla** [comment]
i don't know but it seems a bit strange to put link to home at the right of the navbar together with the logo Which also go to home
in anther words by this there will be a two links to home one in the right and one in left (logo)
what do you think @thejoefriel ?
my recommendation is we don't put anything at the right

**Comment by thejoefriel** [comment]
Yeah I agree this may be unncessary if it's not been part of the signed off wireframes, so will close this for now
