### ISSUE TITLE
warning modal (the website uses local storage)

### ISSUE THREAD

**Issue by othman-shamla** [yalla-coop/curenetics#110]
the modal when pressing (Upload PDFs of patient data) need some adjustment 
![modal](https://user-images.githubusercontent.com/16326221/67158209-f32edc80-f33d-11e9-882e-16070a95dacc.png)

related #90

**Comment by thejoefriel** [comment]
To add to this, this needs: 
- more padding on the top
- more margin around the icon 
- more margin bottom on the header
- Change consent to 'OK' 
- more margin top to the button (or margin bottom on main body text)

**Comment by wright1** [comment]
What adjustments need to be made?

**Comment by MohammedYehia** [comment]
@wright1 I think what Joe mentioned above and also I think it has some problem with mobile view

**Comment by wright1** [comment]
@MohammedYehia Thank you. The way it looks locally and the way it looks on Netlify are very different.
