### ISSUE TITLE
Set up project codebase

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/curenetics#14]
- [x] Set up initial codebase
- [x] Install initial agreed packages
- [x] Sort out git ignore file
- [x] Set up eslint configuration so it works across everyone's editors and let everyone know what set up they need

**Comment by wright1** [comment]
Hi,
So I have set up a very basic code base using create-react-app.
I have installed:
babel
eslint
es-config-airbnb-base
eslint-plugin-import
styled-components
react-router-dom

we may want to customise the linter a bit more, at the moment you can't leave any empty lines in your code, I choose not to change that unless it's the teams preference. As we start coding you may want to customise it a little more.
