### ISSUE TITLE
Bug fixing

### ISSUE THREAD

**Issue by sesola** [yalla-coop/curenetics#149]
Hi guys,

I've attached a loom video link for few things to sort. https://www.loom.com/share/038a9a8c0d114fa8b451b77d282301f8

The 'no data' foe the criteria could change to 'NA'.  Seems better than way, I think

**Comment by thejoefriel** [comment]
Hi @sesola Are you ok to write down the issues as individual bullet points please? Just want to make sure we don't miss any! :)

**Comment by sesola** [comment]
ECOG status: No data
Gleason score: No data
Gleason score: No data 
Disease outside prostate: No data

Everywhere 'no data' applies, should change to NA-not applicable

**Comment by thejoefriel** [comment]
So to clarify this issue is about making sure it shows 'N/A' rather than 'No data'

**Comment by thejoefriel** [comment]
This is now covered in bug issue #157
