### ISSUE TITLE
Agree on tech stack and eslint

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/curenetics#15]
The current plan so far:

Front-end: React, HTML, CSS
Back-end: Is it needed since we'll be connecting to external APIs?
Testing: Supertest
Eslint: Usually airbnb config

Main things to still agree:
- Styled components?
- Testing language (Jest?) 
- Are we setting it up with Create React App?

**Comment by martinbagshaw** [comment]
I'm a big fan of styled components, they definitely help clean out some of the noise that Css classnames and inheritance give.

I might would advocate common styled components for layout and typography - e.g. content containers, cards, and headings for example, with a file for variables such as colours and font sizes.

Another feature of them that is pretty cool and worth looking into are mixins.

**Comment by wright1** [comment]
I'm also a big fan of styled-components, I would like to set up with create-react-app because of speed and ease of use. I haven't used jest to test react components, I think you'll may need to use Enzyme with Jest, I'm willing to give it a go.

**Comment by wright1** [comment]
If we use react will we be using hooks?

**Comment by martinbagshaw** [comment]
@wright1 I believe [react testing library](https://github.com/testing-library/react-testing-library) also works with Jest, and is a popular choice.

Regarding hooks, perhaps go with whatever the majority of people are most comfortable with? Same policy for testing library too I'd say.
