### ISSUE TITLE
New bugs for fixing 

### ISSUE THREAD

**Issue by sesola** [yalla-coop/curenetics#152]
1. Entering the patient data manually, there's no validation on the patient age, you can enter letters in there

2. Gleason score applies only to Prostate cancer. When we are not searching for prostate trials, the Gleason score section shouldn't come up on the screen. 

3. Same goes to Disease within/and outside the prostate. Can we change e.g. to Disease within/outside the breast or disease within/outside the pancreas for the relevant cancer type searches? etc. I can understand this wasn't mentioned before...

If not possible to customise disease inside/outside different types of cancers, we should just disable those 2 options, if people are doing non-prostate cancer searches. 

2) As it searches for clinical trials, the Finding Clinical Trials screen that shows during the loading, some of the text gets cut off on mobile

3) The spacing between lines of the matched trials for patience screen could be larger to make it easier to read over multiple lines.

![image1](https://user-images.githubusercontent.com/41945203/68527397-43b2ad80-02de-11ea-98f4-1b01dafdcd8e.png)
![IMG_3664](https://user-images.githubusercontent.com/41945203/68527398-43b2ad80-02de-11ea-8390-5376fb994c4c.PNG)
![IMG_3665](https://user-images.githubusercontent.com/41945203/68527399-43b2ad80-02de-11ea-85b2-5abb1ffccb1b.PNG)

**Comment by sesola** [comment]
Let me know if bug(1) isn't clear to anyone, I can try and make a video. 

The 2nd picture refers to bug (2)

The 3rd picture refers to bug (3)- ''spacing'' between lines

Picture (1) occurred while I was trying to load on my mobile recently.

**Comment by thejoefriel** [comment]
Hi @sesola 

Unfortunately this one:
> Same goes to Disease within/and outside the prostate. Can we change e.g. to Disease within/outside the breast or disease within/outside the pancreas for the relevant cancer type searches? etc. I can understand this wasn't mentioned before...

Isn't possible to do within scope. We will look to try to hide the ECOG and Gleason score though if the patient has a condition other than prostate cancer.

**Comment by thejoefriel** [comment]
Ok these have been split out into smaller issues so individual team members can take them on :

#153, #154, #155, #156

**Comment by thejoefriel** [comment]
@sesola Please let me know if I've missed anything in these smaller issues :)
