### ISSUE TITLE
Build prototype in Figma

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/curenetics#16]
This will be desktop first with a single breakpoint to accommodate mobiles

- [x] Desktop wireframes
- [x] Mobile wireframes

**Comment by wright1** [comment]
This is where we have gotten with Figma so far
https://www.figma.com/file/BaIHfKxJN8zhXlVoTxlTJu7B/CURENETICS2?node-id=47%3A249
The inital look of the webapp.
