### ISSUE TITLE
Create Common Components

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/curenetics#17]
At the start of the project it's good to identify some common components (e.g. navbar, button ) that we feel we will need so this can be made at an early stage

**Comment by wright1** [comment]
Maybe:
Button component (small medium and large)
Header component - contains the logo
Title component - some pages have 'titles'

**Comment by thejoefriel** [comment]
Yeah I agree with @wright1 - Looking through the wireframes now I just think we need:

- [ ]  Button 
- [ ] Header

**Comment by martinbagshaw** [comment]
I believe #55 may tick a few of these boxes.
Could not help myself. Feel free to amend as required.
