### ISSUE TITLE
Agree File Structure

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/curenetics#18]
I believe this will follow standard React file structure conventions, but issue here to agree it amongst the team.

Initial suggestion:

the suggested file structure

```
├── README.md
├── client
|  ├── package.json
|  ├── public
|  └── src
|     ├── assets
|     ├── components
|     |  ├── Common
|     |  ├── Pages
|     |  ├── App.js
|     |  └── App.test.js
|     ├── constants
|     ├── helpers.js
|     ├── index.js
|     └── styles
|     |   |______ globalStyle.js
|     |   |______ reset.css

```

Technically we don't need to have a 'client' folder but I've left this as this enables us to also build out a back end if ever we need to. Open to changing it though

**Comment by martinbagshaw** [comment]
One thing that we do at my work is name react components as .jsx files in PascalCase, which makes it easy to differentiate between these and helper functions at a glance. 

Should assets (images etc) be in the public folder? What would reside there?

I was also wondering what the 'constants' folder would contain?

**Comment by wright1** [comment]
That file structure makes sense to me. If we use create-react-app (CRA) the file structure can be easily customised.
@mr-bagglesworth  No, assets shouldn't be in the public folder, webpack doesn't read the public folder hence public folder isn't compiled in CRA (althought if pre-fixed with '%PULIC_URL%' assets will be compiled, bad pratice!) . I'm not sure why the favicon is always kept there.

**Comment by martinbagshaw** [comment]
@wright1 cool, guess I've been working on collossal apps where everything gets auto uploaded to a CDN for too long now!

**Comment by MohammedYehia** [comment]
we should put every page in its own folder inside the Pages folder
```
|     ├── Pages
|     |     ├──WelcomePage
|     |     |     ├──index.js
|     |     |     ├── style.css
```
@mr-bagglesworth constants folder is for Route names and other constant urls

**Comment by wright1** [comment]
Do you usually add babel-eslint for parsing errors
