### ISSUE TITLE
Once my files are analysed I am able to see a list of my patients each with structured data pulled from their documents

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/curenetics#23]
Acceptance criteria:

- [ ] List of sections (one per medical record), each showing fields for:
- [ ] Filename
- [ ] Age
- [ ] Postcode (would this be the patient’s home or hostpital?)
- [ ] Type of cancer
- [ ] Gender
- [ ] Subject to being supplied by Jon’s API:
- [ ] ECOG status
- [ ] Gleason score
- [ ] Disease within prostate 
- [ ] Disease outside prostate 
- [ ] If the data hasn’t been pulled out of the document the field will say ‘Data not found in medical record’
- [ ] A link to view the original medical record PDF
- [ ] Data will need to be shown in fields that can be edited - relates to #24 

This will be working potentially with multiple data objects from the JSON object @cloudstartuptech returns to us from the files being analysed, so it will need to iterate through these. 

Wireframe: 
![image](https://user-images.githubusercontent.com/19708921/65892016-7abba800-e39d-11e9-867e-d6b310e68a22.png)

**Comment by thejoefriel** [comment]
Here's a link to where the suggested data structure will be: https://github.com/yalla-coop/curenetics/issues/4

For inputs I think:
- Age: numbers only
- Gender: dropdown (Male / Female)
- cancerType: dropdown, or an autocomplete type thing (for now use this list: https://www.cancercenter.com/cancer-types @sesola are you happy with this total list of cancer types?)
- ECOGStatus: dropdown (0, 1, 2, 3, 4 )
- gleasonScore: dropdown - 3+3, 3+4, 4+3, 4+4, 9-10) 
- Disease in prostate: dropdown (yes / no) 
- Disease outside prostate: dropdown (yes / no)

For these last two, when we get the data from the PDFs we will determine it based on seeing if there's certain keywords in the array i.e. 
- Disease in prostate: if 'disease within prostate' or 'focal disease' are within the keywords array this would be yes. Otherwise it would be no 
- Disease outside prostate: if 'disease outside prostate', 'metastatic disease' or 'advanced disease' in the keywords array this would be yes. Otherwise it would be no

**Comment by othman-shamla** [comment]
@thejoefriel  
i think you miss Patient ID in the shape of the JSON response

**Comment by thejoefriel** [comment]
We don't have that any more @othman-shamla in order to protect their identity. Instead we will have the filename or filereference so we know which file in our local storage it's referring to

**Comment by thejoefriel** [comment]
I've updated the main description of the issue to reflect this now

**Comment by othman-shamla** [comment]
@thejoefriel  okay, that's good
