### ISSUE TITLE
I am able to submit my patients details to find clinical trials

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/curenetics#25]
Acceptance criteria:

- [ ] ‘Find Clinical Trials’ button at the bottom of the list of sections
- [ ] Query Jamie’s API (@jbrough) to find trials in the UK within the last year that match the values submitted
- [ ] We may filter to only return trials that are currently recruiting or will recruit soon, to keep the file size and number down

**Comment by thejoefriel** [comment]
Hey @MohammedYehia - this is related to the issue you're working on. This is the issue where we need to build out the filtering functions that query the API so we return an object with an array of clinical trial result objects that are then used on the issue you're working on #27 

Feel free to assign yourself to this issue. It's quite a big one though so might be something to pair on :)

**Comment by MohammedYehia** [comment]
@thejoefriel 
this is the one related to this issue, right?

![1](https://user-images.githubusercontent.com/7594617/66331874-2637a000-e93c-11e9-87b3-5947517c4cb5.PNG)
