### ISSUE TITLE
Deploy on Netlify

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/curenetics#40]
- [ ] Create an account for Sola and add to the App info spreadsheet in Resources issue #9 
- [ ] Add relevant initial env variables and store in App info spreadsheet in Resources issue #9 
- [ ] Set up continue deployment on Netlify

**Comment by martinbagshaw** [comment]
[Deployed at](https://curenetics-app.netlify.com/)

I suggest we remove the old app, and use that domain name at some point:

[https://curenetics.netlify.com/](https://curenetics.netlify.com/)
