### ISSUE TITLE
Curenetics.BrandBook.pdf

### ISSUE THREAD

**Issue by susanX** [yalla-coop/curenetics#45]
Would you like us to use the logo, fonts and colours in the Curenetics Branding Book?

Or can we use the logo we developed in the earlier Curenetics project (blue dots connected in the shape of a C which had a science feel). 
We also used blue colour for tabs and backgrounds (we are thinking of adding another colour to this). Plus we used the sans serif Google font Lato.

**Comment by thejoefriel** [comment]
This got resolved in Slack with us agreeing to follow the brand guidelines so closing this comment now
