### ISSUE TITLE
Store uploaded PDFs on local storage

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/curenetics#80]
Relates to #21 

We need the PDFs of the medical records submitted to be stored on local storage in order that we can make them available to view as PDFs for the user to check against the data extracted. 

We would also rename each file so no sensitive data is accidentally sent in the filename (e.g. the patient's name), before we store in local storage and send on the post request to be analysed.

Reminder of logic flow here: https://drive.google.com/file/d/16EwBESJCygD7HGn7GoucdvoHMqAnsJN2/view?usp=sharing

When a user hits submit
- [ ] Rename each file with a unique identifier
- [ ] Store file in local storage
- [ ] When user leaves app, remove files in local storage

**Comment by othman-shamla** [comment]
i dont think there a need for store the pdfs on local storage or something because 
i assume we can just store the reference to file in context or the App.js state to pass it to other pages
@thejoefriel
