### ISSUE TITLE
Agree best method to imitate the APIs

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/curenetics#82]
Since we are still waiting for both APIs to be built, we are currently working with example JSON data. In order to complete our part of this project we need to imitate the process as closely as possible to minimise friction when the APIs are ready to be swapped in. 

Is it worth setting up a basic back end where both example JSON data files can be hosted (the patient data one and the clinical trials one) so we can at least build the front end using post requests to a certain url, as then it may be simpler to swap in an external API url?

To confirm this wouldn't need to store PDFs as that arguably would be too much a waste of time creating something that we wouldn't then use, but it would have the JSON data so we can replicate post requests where we send something and get JSON data returned.

What do people think?

**Comment by MohammedYehia** [comment]
I don't think we need a whole API for this we can use two JSON files(one is the patientDummyData and the other one is the clinical trial JSON result) and make a request for them and we can imitate the API suing a promise and set timeout  

right I am sending a request directly to Github
