### ISSUE TITLE
Update manual entry to match edit patient

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/curenetics#84]
At the moment the manual entry has freeform text rather than dropdowns. Please refer to how it looks in the edit section and copy this.

**Comment by othman-shamla** [comment]
seems that this page was build by martin in his first PR without referring his work to the issue #83
i will do the changes for accessibility and small changes that i notice it for the page and delete the page that duplicated

https://curenetics-app.netlify.com/enter-patients
