### ISSUE TITLE
Add copy to About Page

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/curenetics#87]
**COPY**
In diseases, such as cancer, through our AI algorithms, domain expertise and ability to analyze complex medical data, we are giving patients hope by helping to recruit them to most suitable clinical trials. At the same time helping trial groups meet recruitment targets and hence save costs and reduce time to trial completion.

About 4% of patients in the UK end up being recruited to clinical trials despite over 70% of patients saying they would like to be offered opportunity to be involved in a clinical trial. 2/3rd of clinical trials still fail in the UK despite best efforts. We are determined to turn around this trend by improving patient access and engagement with trials and providing hope of new treatments and even cure for various diseases to millions of people around the world.

**Comment by susanX** [comment]
For Sola's attention. Suggested small edits on copy below

Through our AI algorithms, domain expertise and ability to analyse complex medical data, we are giving patients hope, from diseases, such as cancer. By helping to recruit them to the most suitable clinical trials and helping trial groups meet recruitment targets, we are able to save costs and reduce time to trial completion.

Although over over 70% of patients saying they would like to be offered the opportunity to be involved in a clinical trial, only 4% of patients in the UK end up being recruited to clinical trials. Two thirds of clinical trials still fail in the UK despite best efforts. We are determined to turn around this trend by improving patient access and engagement with trials to provide hope of new treatments—and even a cure—for various diseases to millions of people around the world.

**Comment by sesola** [comment]
I agree Susan. Thanks for the edits
