### ISSUE TITLE
Small edit to overall found trials list

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/curenetics#89]
- Change 'Gleason level' to 'Gleason score'

**Comment by othman-shamla** [comment]
just to be sure, are you talking about the Paragraph in the header of the page?

![Screenshot from 2019-10-20 17-18-43](https://user-images.githubusercontent.com/16326221/67160914-2f723500-f35e-11e9-81bc-8d6d0feaf331.png)

**Comment by thejoefriel** [comment]
Yes that's right! Maybe to be safe, do a search of the codebase for 'Gleason level' and replace with Gleason score if you find it anywhere else
