### ISSUE TITLE
Add warning message on the landing page

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/curenetics#90]
We need to load the pop up that explains the use of data etc, as is in the Figma wireframes.

**Comment by thejoefriel** [comment]
Also please refer to this issue as Sola raised a few more sentences that we should include in the warning box: https://github.com/yalla-coop/curenetics/issues/51

**Comment by susanX** [comment]
Works well! And looks good. Just a few small points. 
- Make button oranage before it 's clicked. Capital C for Consent.
- Add more space top and bottom svg.
- Make Title smaller (on Figma it is just 2px bigger than text) black      , add space under the title.
- Add a bit more padding between the text and button and the box border.
- The inactive page on Figma has white 50% added to it to give the paler look.

**Comment by susanX** [comment]
https://github.com/yalla-coop/curenetics/issues/51
Edits to clear warning box-->

Medical information extracted is immediately pseudo-anonymised and then encrypted before analyses
[note: change: 4th word should be is not are]

Medical professionals must only used this app on a secure or trust-approved computer. The uploaded files(s) will be stored locally but wiped when you close the app.

This current software iteration is only optimised for scientific and research purposes. It must not serve as aid in clinical decision making.
